builds:
  1932b81da9c82c639b368d8a4370bcd1c2eff86b4b029435c61db0634851d0b0:
    version: 1932b81da9c82c639b368d8a4370bcd1c2eff86b4b029435c61db0634851d0b0
    blobstore_id: 9858090b-75be-404e-6753-50af5980f718
    sha1: sha256:ccac3ebdd9ab75ffac5b9986e4a01ed4706bb4cde0a539f76ad5479b5f518227
  45062aefa4be8e9f0a2af53e5591e04be5a8db0b:
    version: 45062aefa4be8e9f0a2af53e5591e04be5a8db0b
    blobstore_id: f932657e-3a77-414d-b90d-fe2c2a42f138
    sha1: 9781cde8df0a9ecee0c60516b734d7c140536415
  6ef4feeaf01ffb4d27b5f2f7094b0380d2624019:
    version: 6ef4feeaf01ffb4d27b5f2f7094b0380d2624019
    blobstore_id: e09419a6-27a8-4a4f-89b9-5dbf4c211ebe
    sha1: 280bd6d784531e14eaa680e44e81568c54cf0899
  800b4c9c506c219cbfec65ee48ecb1b650138b955db5342490dc8b13bfca73b3:
    version: 800b4c9c506c219cbfec65ee48ecb1b650138b955db5342490dc8b13bfca73b3
    blobstore_id: 29876090-3f25-41cc-62ad-86b1e0134f71
    sha1: sha256:980bf631471b0abbfad52f56de4197f1e646580cc34d1c0715a6cb2907cb49dd
  8f6669a86bc2b96b7b6d084795b466a11f695d66:
    version: 8f6669a86bc2b96b7b6d084795b466a11f695d66
    blobstore_id: 4f17f214-e73c-47a1-9e1e-1818650b9c5f
    sha1: 28686a69a667ba965965469e22792be375601d3c
  eb4e9c9e415525e946bb55b1b3057e0224d5f829:
    version: eb4e9c9e415525e946bb55b1b3057e0224d5f829
    blobstore_id: 5d0ed66b-6a19-4728-77cc-3745d8e99540
    sha1: 7c38c5bb13b9bf6ae5961bb572b7f31c9f9095b1
format-version: "2"
