builds:
  0d43e6cab4418fe262d9f92a070f42b8ab850c7f:
    version: 0d43e6cab4418fe262d9f92a070f42b8ab850c7f
    blobstore_id: 0103264a-97b2-4679-606b-a85b40930b32
    sha1: b7f3c9d0c902aa4c5342557ae8d450979f5bdbd6
  11b7b8636befb86814c62eb532a66b8734dd96b37f52f3a78807028a5b56a108:
    version: 11b7b8636befb86814c62eb532a66b8734dd96b37f52f3a78807028a5b56a108
    blobstore_id: 391b7cc6-d72f-4987-50da-c289a519b587
    sha1: sha256:4ff7f62adc8459f950776c9df46ed0c33d40c7e8a2866a35360fcba06ed02381
  18ae5db1a57beff82b3657235d51953a6dafc36b:
    version: 18ae5db1a57beff82b3657235d51953a6dafc36b
    blobstore_id: a5c379c4-12be-40fd-7a1b-0ae8208a4380
    sha1: 30891a54234fdb86c2d90f2428a4588e3c7003bc
  68c5ed3f613d3b3a03be0c54c2785762baabe990:
    version: 68c5ed3f613d3b3a03be0c54c2785762baabe990
    blobstore_id: e6f1e3d1-826d-4bb2-73eb-2c86cab6c6c2
    sha1: 624d566ce55c3b9832e6da722a0093383f40b86e
  738e93504e9b79643fef3f22479f095097a88b56:
    version: 738e93504e9b79643fef3f22479f095097a88b56
    blobstore_id: 55091671-4b1a-4916-61d6-e1ddeeab783b
    sha1: 0719a9e62f0128344b0f964840570aa6bd8c8561
  7bf1c19fb586ca3fedf15d991c9dd0b34ee31d06:
    version: 7bf1c19fb586ca3fedf15d991c9dd0b34ee31d06
    blobstore_id: 1affe868-1db1-4786-af30-fbae046b06dd
    sha1: 1e98d4e4bb74ebda3e944d5f8fb910704871a444
  7d6a425d3b12e3288adb8aef0490d86d40647ed712a5b833fef1d748ae5f7587:
    version: 7d6a425d3b12e3288adb8aef0490d86d40647ed712a5b833fef1d748ae5f7587
    blobstore_id: d0499754-f5e8-43a7-5212-0e3fb6a968a0
    sha1: sha256:ff1f1d3b24d4f0b1f16de13f5330289c350928030cb0cf84e0a95e772f57b129
  84813cebb7d13b4326b9ce7948e515e9c898f857:
    version: 84813cebb7d13b4326b9ce7948e515e9c898f857
    blobstore_id: 8998a15b-0c90-4cb8-64e4-6e089351815a
    sha1: 02aeaf9607e7d788edb2376db1660ac563709ed2
  a8561c908f85bc87e393459c985ab99ec23a96ef:
    version: a8561c908f85bc87e393459c985ab99ec23a96ef
    blobstore_id: 7e7b8211-74eb-4651-69e4-2d4a2e5f6dae
    sha1: a419628332971e4081bd7410bc214039309effed
  a929106f17d24fa9f5f22a07b0a97f9d5df63c6a:
    version: a929106f17d24fa9f5f22a07b0a97f9d5df63c6a
    blobstore_id: ad37b5c4-47bd-4961-6ace-21171f30cb30
    sha1: 886ab78e5cb552a323cfe965f7f21969a5ebe977
  b76343f51a3f298b86e4b7fe36b2cc53d649e9a4:
    version: b76343f51a3f298b86e4b7fe36b2cc53d649e9a4
    blobstore_id: b418bd95-3d79-4891-af63-16c3c7fffe1f
    sha1: f55e6f7b1155d33d914be09ec2c2aafb6fd8c398
  ba1be3b3156bf5e02a9c84e3ea7b36d6a7d85cb8:
    version: ba1be3b3156bf5e02a9c84e3ea7b36d6a7d85cb8
    blobstore_id: 858ee81b-2fb6-4404-4def-14cdf3636101
    sha1: 1ff4c4808c1b012bdc6f0bb7ace7e260086f0d81
  bb90f42b964513a8fd8a4fb906de0a51a79ac576:
    version: bb90f42b964513a8fd8a4fb906de0a51a79ac576
    blobstore_id: 4e71160f-9709-4438-722d-82abe1e35d5e
    sha1: 0b5806b75123db7db4dec376f3c5acb65562ab03
  d5a9470049b1d33746c603e7625558de3914b0cf:
    version: d5a9470049b1d33746c603e7625558de3914b0cf
    blobstore_id: 76413a94-349f-42a4-868a-0c12f71f98d7
    sha1: 997f024ce378112d4aa9a624c0bc0fdafa33d407
  d748d5de31b8cd816e8d5f11834ede803d777c84c568db54b65ae8ccf50fa8f4:
    version: d748d5de31b8cd816e8d5f11834ede803d777c84c568db54b65ae8ccf50fa8f4
    blobstore_id: 7f5920d0-b940-4542-47aa-4d00656a3174
    sha1: sha256:df3b5a6bf0583f5ab3f2c578685b6368edd42b66de6c8fb0a36110e6ee5b9303
  d7efe7a300b5fff05c2317c0184665c1710b46b2:
    version: d7efe7a300b5fff05c2317c0184665c1710b46b2
    blobstore_id: d1052eab-6259-4eb5-4a3f-a3e8aafdecbb
    sha1: ba5dc4e9366de70f682a7ad67982f5fa977f63ad
  f6a6136147451c29d92867e29031e780c61b9bd6:
    version: f6a6136147451c29d92867e29031e780c61b9bd6
    blobstore_id: 8d890263-be8b-403d-5b36-c1c0cfa937f1
    sha1: 3b66591ccc8c446bebfb5f6bfa2d045d6a3786f0
format-version: "2"
