apt/lvm2/libdevmapper-event1.02.1_2:1.02.77-6ubuntu2_amd64.deb:
  size: 10812
  object_id: 67e8628d-c7a4-4182-8fdd-4cddd60bcaa0
  sha: 2873ddde9dfa3897918fb48a470fdf6ba511e182
apt/lvm2/libreadline5_5.2+dfsg-2_amd64.deb:
  size: 130428
  object_id: 2f4d6377-7c29-470b-a917-acdcb05e0c75
  sha: 5e0e4d8cbad5302244c06f79f74497a30754f8af
apt/lvm2/lvm2_2.02.98-6ubuntu2_amd64.deb:
  size: 469600
  object_id: 3bbf149a-e117-4d5e-9667-3632ae9c0b95
  sha: 52bca696115b57cd1ad1aa5afe187001f72c5ee2
apt/lvm2/watershed_7_amd64.deb:
  size: 11356
  object_id: a72d0857-ae9b-4b2f-b5b6-725bee7006d9
  sha: 5c02014b7daecff6c0a6367996d2819d9b16745e
aws-cli/awscli-bundle.zip:
  size: 7500720
  object_id: 65e17a4e-644d-456c-7451-fa4de7c68ebd
  sha: 0ad44b243d41d788418cc86bd6179ab002224267
docker/aufs-tools_20120411-3_amd64.deb:
  size: 91762
  object_id: b95dca91-e344-4c54-a908-68651b81264f
  sha: 2dfc1fe386cd3f05ac7e0b4ebcf3ebc8a7f3b04d
docker/autoconf-2.69.tar.gz:
  size: 1927468
  object_id: 83391b7e-d4bf-4052-92bb-e708f33e25c6
  sha: 562471cbcb0dd0fa42a76665acf0dbb68479b78a
docker/docker-17.06.1.tgz:
  size: 29699281
  object_id: 128671d4-33ef-4cad-8239-0ae39d38f55d
  sha: 01c73e6548e588e6d5bdc3dea45bb90239516e4b
golang/go1.6.2.linux-amd64.tar.gz:
  size: 84840658
  object_id: abc1be7b-ce69-4442-a841-cfc0a88109e4
  sha: b8318b09de06076d5397e6ec18ebef3b45cd315d
golang/go1.8.3.linux-amd64.tar.gz:
  size: 90029041
  object_id: 531dbe5c-f65b-4c3a-a524-c630a7762567
  sha: 838c415896ef5ecd395dfabde5e7e6f8ac943c8e
jq/jq:
  size: 497799
  object_id: 61d27ef5-32cc-439d-6842-97be75dae6fb
  sha: e820e9e91c9cce6154f52949a3b2a451c4de8af4
keepalived/keepalived-2.0.5.tar.gz:
  size: 848206
  object_id: eb0cd1af-1b58-4349-7386-9b7f5685b0c2
  sha: b950ff1931c1062f34d57dfef24473b4c6b60209
kubernetes-1.11.1/kube-apiserver:
  size: 185513080
  object_id: 03a0392c-f620-4ccb-73ca-48b0a1aeff33
  sha: 6805ea84a3fa1653219e75b3b99f47547e53380e
kubernetes-1.12.4/kube-apiserver:
  size: 192825094
  object_id: 99e8f3b2-192f-4ac3-487f-18245b786565
  sha: 265d1fd6c34785b5610b5a3ce95d6af755c9c97f
libseccomp/libseccomp-2.3.3.tar.gz:
  size: 564546
  object_id: 4e749385-3bc6-45b5-7a08-906c3cf97573
  sha: 89b1f35447b1891a3051de979dc92ad9f7258b60
node/node-v8.14.0-linux-x64.tar.xz:
  size: 11322764
  object_id: 35d41cae-73bd-48a4-7284-79e92455ded2
  sha: b74889a4cbfda92760311826d13726939190dc60
python/Python-2.7.6.tar.xz:
  size: 10431288
  object_id: 7f61b922-e0de-47ac-6eec-fb0b53a2e6ea
  sha: 8321636af2acbeaa68fc635d7dda7369ed446a80
yaml2json/yaml2json:
  size: 2349240
  object_id: b3d57a81-3790-43a4-69eb-c2bcb02fcc54
  sha: 8386a711bfc5f8dca5239f81277cb910ace5d7c2
